lib/djvAV/SequenceIO.cpp: add missing '<thread>' include
Without the change build fail on `gcc-13` as:

    DJV/lib/djvAV/SequenceIO.cpp: In lambda function:
    DJV/lib/djvAV/SequenceIO.cpp:674:51:
      error: 'sleep_for' is not a member of 'std::this_thread'
      674 |                                 std::this_thread::sleep_for(std::chrono::milliseconds(timeout));
          |                                                   ^~~~~~~~~